apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: cleanup-task
spec:
  steps:
    - name: cleanup
      image: busybox
      script: |
        #!/bin/sh
        echo "Cleaning up temporary files..."
        rm -rf /tmp/*

---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: nose-test-task
spec:
  steps:
    - name: run-nose-tests
      image: python:3.11
      script: |
        #!/bin/sh
        pip install nose
        nosetests
